### ISSUE TITLE
Don't hard code malloc/free invocations

### ISSUE THREAD

**Issue by nemequ** [davidcatt/FastARI#3]
I'd like to be able to use a custom function to allocate and free memory instead of having FastARI just call malloc/free.

It looks like there is a single buffer allocated during both compression and decompression, and they are the same size.  How about just allowing the caller to pass a `void* workmem` parameter and expose the necessary size in the header?  It's not without precedent; several libraries do that (LZO comes to mind), and it has the advantage that the buffer can be shared across multiple compress/decompress calls.  For single-threaded applications you could even avoid dynamically allocated memory altogether.

**Comment by davidcatt** [comment]
Thanks!  I've been away during the holidays so I didn't have time to implement the fixes.  I'll look into the potential data errors (it appears to work without issue when FA_USE_EOF is defined).

**Comment by nemequ** [comment]
> Thanks! I've been away during the holidays so I didn't have time to implement the fixes. I'll look into the potential data errors (it appears to work without issue when FA_USE_EOF is defined).

That explains why Squash works, and for short files why it's always the last few bytes.  *Very* good to know you can reproduce it :)
